# Generated by Django 2.1.3 on 2018-11-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooseball', '0004_teamtable_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtable',
            name='team1score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchtable',
            name='team2score',
            field=models.IntegerField(default=0),
        ),
    ]
