# Generated by Django 2.1.3 on 2018-11-02 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooseball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='player1_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='player2_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='team_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
