# Generated by Django 2.1.3 on 2018-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooseball', '0002_auto_20181102_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtable',
            name='id',
        ),
        migrations.AlterField(
            model_name='teamtable',
            name='team_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
