# Generated by Django 2.1.3 on 2018-11-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooseball', '0003_auto_20181102_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtable',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
