# Generated by Django 2.1.3 on 2018-11-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooseball', '0005_auto_20181102_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtable',
            name='matches_draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamtable',
            name='matches_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamtable',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
