# Generated by Django 2.1.3 on 2018-11-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooseball', '0007_auto_20181103_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='team1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matchtable',
            name='team2',
            field=models.CharField(max_length=200),
        ),
    ]
